version: '3.2'
services:
  interview-Backend-api:
    image: phoutthasv/Interview-Backend
    build: ../
    ports:
      # - "3004-3006:9085"
      - "5969:5969"
    restart: always
    env_file:
    - .env
  
    